[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.1"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
moonbase = "${MOONBASE_RPC_URL}"

[etherscan]
moonbase = { key = "${ETHERSCAN_API_KEY}" } 